@startuml

skinparam classAttributeIconSize 0
left to right direction

package "App\\modelo" {
class Conexion {
  -conex
  -conexSG
  -llavePrimaria
  -campoWhitelist
  +getConex()
  +getConexSG()
  +conex()
  +conexSG()
  +getConexion()
  +verificarExistencia()
  +verificarExistenciaPropia()
  +crearConexion()
}
class ModeloArticulosInventario {
  +ProcesarDatos()
  +GenerarCodigoClub()
  +ConsultarAgrupado()
  +CargarCombos()
  +IncluirArticulo()
  +ModificarArticulo()
  +EliminarArticulo()
  +ReincorporarArticulo()
  +ConsultarArticulosLibres()
  +CambiarEstatus()
}
Conexion <|-- ModeloArticulosInventario
class ModeloAsignaciones {
  -id_asignacion
  -codigo_atleta
  -codigo_articulo
  -fecha_asignacion
  -estatus
  -filtro
  -fecha_inicio
  -fecha_fin
  -mostrar_inactivos
  -accion_actual
  -objArticulos
  +setArticulos()
  +ProcesarDatos()
  +ConsultarAsignaciones()
  +IncluirAsignacion()
  +ModificarAsignacion()
  +AnularAsignacion()
  +CambiarEstatusAsignacion()
  +ValidarExpresiones()
}
Conexion <|-- ModeloAsignaciones
class ModeloAtletas {
  -id
  -doc_identidad
  -nombre
  -apellido
  -telefono
  -direccion
  -representante
  -posicion
  -genero
  -categoria
  -fecha_nac
  -estatus
  -edad
  -foto
  -dorsal
  -peso_kg
  -estatura_cm
  -motivo_retiro
  -ObjCat
  -ObjRep
  -ObjPos
  +setModeloCategorias()
  +setModeloPosiciones()
  +setModeloRepresentantes()
  +ProcesarDatos()
  +Consultar()
  +ConsultarAtletas()
  +Incluir()
  +Modificar()
  +Buscar()
  +ConsultarCumple()
  +Eliminar()
  +Reinscribir()
  +ValidarExpresiones()
}
Conexion <|-- ModeloAtletas
class ModeloAutomatizacion {
  +EjecutarProcesos()
  +ObtenerAtletasInscripcionActiva()
  +GenerarCargosAnuales()
  +GenerarCargosMensuales()
  +GenerarMultas()
  +ActualizarEstatusTorneos()
  +obtenerMonedaBase()
  +insertarCargo()
}
Conexion <|-- ModeloAutomatizacion
class ModeloBitacora {
  +RegistrarAccion()
  +Consultar()
}
Conexion <|-- ModeloBitacora
InterBitacora <|.. ModeloBitacora
class ModeloCatalogo {
  -id_catalogo
  -nombre
  -stock_minimo
  -id_categoria
  -talla
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Eliminar()
  +ValidarExpresiones()
}
Conexion <|-- ModeloCatalogo
class ModeloCategoriaCatalogo {
  -id_categoria
  -nombre
  -descripcion
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Eliminar()
  +ValidarExpresiones()
}
Conexion <|-- ModeloCategoriaCatalogo
class ModeloCategorias {
  -id
  -nombre
  -edad_min
  -edad_max
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Eliminar()
  +verificarCategoria()
  +ValidarExpresiones()
}
Conexion <|-- ModeloCategorias
class ModeloConceptos {
  -id
  -nombre
  -monto
  -estatus
  -frecuencia
  -dias
  +ProcesarDatos()
  +Consultar()
  +ConsultarConcepto()
  +Incluir()
  +Modificar()
  +Buscar()
  +Eliminar()
  +Estatus()
  +ValidarExpresiones()
}
Conexion <|-- ModeloConceptos
class ModeloCuentasCobrar {
  -codigo_cargo
  -codigo_concepto
  -codigo_atleta
  -monto_total
  -fecha_emision
  -estatus
  +ProcesarDatos()
  +Consultar()
  +ConsultarCargos()
  +Incluir()
  +Modificar()
  +Buscar()
  +Eliminar()
  +validarFrecuencia()
  +obtenerMonedaBaseId()
  +ModificarEstatus()
  +ConsultarAtrasados()
}
Conexion <|-- ModeloCuentasCobrar
class ModeloDevoluciones {
  -id_devolucion
  -id_asignacion
  -id_estado
  -fecha_devolucion
  -observacion
  -objAsignaciones
  -objEquipamientos
  +setAsignaciones()
  +setEquipamientos()
  +ProcesarDatos()
  +ConsultarDevoluciones()
  +VerificarExistenciaAsignacion()
  +VerificarExistenciaDevolucion()
  +IncluirDevolucion()
  +ModificarDevolucion()
  +AnularDevolucion()
}
Conexion <|-- ModeloDevoluciones
class ModeloEquipos {
  +ProcesarDatos()
  +Consultar()
  +ConsultarEquipos()
  +ConsultarAtletasParaAsignacion()
  +ConsultarAtletasAsignadosEquipo()
  +GuardarDetallesEquipo()
  +Incluir()
  +Modificar()
  +Buscar()
  +Eliminar()
  +ValidarExpresiones()
}
Conexion <|-- ModeloEquipos
class ModeloEstadisticas {
  -id
  -atleta
  -participacion
  -goles
  -asistencias
  -penalizaciones
  -goles_c
  -partidos
  -average
  -ModeloHistorial
  -ModeloParticipaciones
  +setHistorial()
  +setParticipaciones()
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Buscar()
  +Modificar()
  +Eliminar()
  +validarEstadisticaDuplicada()
  +validarEstadisticaDuplicadaPropia()
}
Conexion <|-- ModeloEstadisticas
class ModeloEstadoFisico {
  -id_estado
  -nombre
  -nivel_estado
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Eliminar()
}
Conexion <|-- ModeloEstadoFisico
class ModeloHistorial {
  +ProcesarDatos()
  +consultarCurriculum()
  +verificarHistorialIndividual()
  +verificarHistorialGrupal()
}
Conexion <|-- ModeloHistorial
class ModeloInicio {
  +ProcesarDatos()
  +IniciarSesion()
}
Conexion <|-- ModeloInicio
class ModeloMetodosPago {
  -id
  -nombre
  -nec_referencia
  -bloqueo
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Buscar()
  +ConsultarMetodos()
  +Eliminar()
  +Bloquear()
}
Conexion <|-- ModeloMetodosPago
class ModeloModulos {
  -id
  -nombre
  -descripcion
  +ValidarExpresiones()
  +ProcesarDatos()
  +Consultar()
  +Modificar()
}
Conexion <|-- ModeloModulos
class ModeloMonedas {
  -id
  -nombre
  -abreviatura
  -simbolo
  -bloqueo
  +ProcesarDatos()
  +Consultar()
  +ConsultarMonedas()
  +Buscar()
  +obtenerMonedaBase()
  +Incluir()
  +Modificar()
  +Eliminar()
  +Bloquear()
  +SelecMonedaBase()
  +obtenerCantidadTotalMonedas()
  +obtenerCantidadMonedasActivas()
  +obtenerDatosMoneda()
}
Conexion <|-- ModeloMonedas
class ModeloNotificaciones {
  +registrarYNotificar()
  +consultarPorUsuario()
  +verificarChequeoDeHoy()
  +marcarComoVisto()
}
Conexion <|-- ModeloNotificaciones
class ModeloPagos {
  -id
  -id_cuenta
  -id_metodo
  -id_moneda
  -monto
  -fecha
  -fecha_f
  -referencia
  -estatus
  -anulados
  -objCuentas
  -objTasa
  -objMonedas
  +setCuentas()
  +setMonedas()
  +setTasa()
  +ProcesarDatos()
  +ConsultarTasasDisponibles()
  +Consultar()
  +ConsultarReporte()
  +agruparDetallesPagos()
  +Incluir()
  +RegistrarVuelto()
  +Eliminar()
  +ConsultarMontoAbonado()
}
Conexion <|-- ModeloPagos
class ModeloPalmares {
  -id
  -id_torneo
  -id_atleta
  -id_equipo
  -id_premio
  -tipo_palmares
  -modeloParticipaciones
  -modeloPremios
  +setModeloParticipaciones()
  +setModeloPremios()
  +ProcesarDatos()
  +ConsultarIndividual()
  +ConsultarGrupal()
  +agruparPalmaresIndividual()
  +agruparPalmaresGrupal()
  +Incluir()
  +Modificar()
  +Eliminar()
  +BuscarIndividual()
  +BuscarGrupal()
}
Conexion <|-- ModeloPalmares
class ModeloParticipaciones {
  -codigo_participacion
  -codigo_torneo
  -codigo_equipo
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Buscar()
  +Modificar()
  +Eliminar()
  +validarParticipacionIndividual()
  +validarParticipacionGrupal()
  +validarParticipacionDuplicadaPropia()
}
Conexion <|-- ModeloParticipaciones
class ModeloPermisos {
  -id
  -nombre
  -descripcion
  -clave
  -modulo
  -bloqueo
  +ValidarExpresiones()
  +ProcesarDatos()
  +Consultar()
  +Buscar()
  +Incluir()
  +Modificar()
  +Bloqueo()
}
Conexion <|-- ModeloPermisos
class ModeloPosiciones {
  -id
  -nombre
  -abreviatura
  -descripcion
  +ProcesarDatos()
  +Consultar()
  +Buscar()
  +Incluir()
  +Eliminar()
  +Modificar()
  +verificarPosiciones()
  +ValidarExpresiones()
}
Conexion <|-- ModeloPosiciones
class ModeloPremios {
  -codigo_premio
  -nombre
  -tipo
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Buscar()
  +Eliminar()
  +validarTipoPremio()
}
Conexion <|-- ModeloPremios
class ModeloPrincipal {
  +ConsultarTarjetas()
  +ConsultarGraficos()
  +ConsultarCalendario()
}
Conexion <|-- ModeloPrincipal
class ModeloRecuperacion {
  -codigo
  -cedula
  -conexion
  +ProcesarDatos()
  +ComprobarCedula()
  +Reenviar()
  +ComprobarCodigo()
  +enviarCorreo()
}
Conexion <|-- ModeloRecuperacion
class ModeloReportes {
  +Consultar()
  +ConsultarRecaudacion()
  +ObtenerCategorias()
  +ObtenerMonedas()
  +ObtenerConceptos()
  +ConsultarInventario()
  +ObtenerCategoriasCatalogo()
  +ConsultarRendimiento()
  +ObtenerAtletas()
  +ObtenerTorneos()
}
Conexion <|-- ModeloReportes
class ModeloRepresentantes {
  -id
  -cedula
  -nombre
  -apellido
  -telefono
  -direccion
  -nacionalidad
  +ValidarExpresiones()
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Buscar()
  +Eliminar()
  +verificarRepresentantes()
}
Conexion <|-- ModeloRepresentantes
class ModeloRespaldo {
  -mysqlPath
  -dbName
  -user
  -pass
  -rutaSegura
  +ProcesarDatos()
  +ConsultarBackups()
  +GenerarBackup()
  +RestaurarBackup()
  +EliminarBackup()
}
Conexion <|-- ModeloRespaldo
class ModeloRoles {
  -objPermiso
  +procesarDatos()
  +setPermiso()
  +consultar()
  +Buscar()
  +CargarPermisos()
  +Incluir()
  +Modificar()
  +GuardarPermisos()
  +Eliminar()
  +ValidarExpresiones()
}
Conexion <|-- ModeloRoles
class ModeloTasaCambios {
  -codigo_tasa
  -codigo_moneda
  -fecha
  -valor_tasa
  -tipo
  +ProcesarDatos()
  +Consultar()
  +ConsultarTasasDisponibles()
  +ConsultarTasaDelDia()
  +ConsultarMonedasNoBase()
  +Registrar()
  +Sincronizar()
  +obtenerTasaDelDia()
  +obtenerTasaDeAPI()
}
Conexion <|-- ModeloTasaCambios
class ModeloTorneos {
  -codigo_torneo
  -nombre
  -fecha_inicio
  -fecha_fin
  -ubicacion
  -estatus
  +ProcesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Eliminar()
  +ValidarExpresiones()
  +ConsultarProximos()
}
Conexion <|-- ModeloTorneos
class ModeloUsuarios {
  -id
  -cedula
  -nombre
  -apellido
  -telefono
  -correo
  -rol
  -foto
  -bloqueo
  -permisos_seleccionados
  -obj_roles
  +procesarDatos()
  +Consultar()
  +Incluir()
  +Modificar()
  +Eliminar()
  +Bloquear()
  +Buscar()
  +ConsultarRoles()
  +CargarPermisosUsuario()
  +GuardarPermisosUsuario()
  +registrarUltimoIngreso()
  +EditarPerfil()
}
Conexion <|-- ModeloUsuarios
}

@enduml